a = input('Digite algo: ')
print('O tipo primitivo é? {}'.format(type(a)))
print('Está tudo maiusculo? {}'.format(a.isupper()))
print('Está tudo minusculo? {}'.format(a.islower()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumerico? {}'.format(a.isalnum()))
print('Tem espaços? {}'.format(a.isspace()))
print('Está capitalizada? {}'.format(a.istitle()))
